default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  encoding: unicode
  database: myapp_development
  pool: 5
  password:

test:
  <<: *default
  database: sqlite3

production:
  <<: *default
  database: sqlite3